name: electricity_market
version: "1.0.0"
config-version: 2

profile: electricity_market

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  electricity_market:

    staging:
      +schema: STAGING
      +materialized: view
      +tags: ["staging"]

    intermediate:
      +schema: INTERMEDIATE
      +materialized: table
      +tags: ["intermediate"]

    marts:
      +schema: MART
      +materialized: table
      +tags: ["mart"]
